# shared_agents.py  (c) Terence Lim
import os
from dotenv import load_dotenv
from pydantic_ai import Agent
from pydantic_ai.mcp import MCPServerStreamableHTTP
from pydantic_ai.models.google import GoogleModel, GoogleModelSettings

load_dotenv()


def create_model():
    model_name = os.getenv("MODEL_NAME", "")
    model = GoogleModel(model_name)
    model_parameters = GoogleModelSettings(google_thinking_config={"include_thoughts": False})
    return model_name, model, model_parameters


def create_agents():
    _, model, model_parameters = create_model()

    research_server = MCPServerStreamableHTTP(url="http://localhost:8000/mcp", read_timeout=900)
    report_server = MCPServerStreamableHTTP(url="http://localhost:8001/mcp", read_timeout=900)
    coding_server = MCPServerStreamableHTTP(url="http://localhost:8003/mcp", read_timeout=900)

    research_agent = Agent(
        name="Factor Research Agent",
        model=model,
        model_settings={"temperature": 0.0, **model_parameters},
        system_prompt="""
You are a Factor Research Agent who interacts with the user, answers general knowledge questions,
and uses tools provided to retrieve historical data from CRSP and Compustat databases, and 
construct or manipulate factor or portfolio characteristics, weights or returns in Panel data sets,
Before calling any tool to manipulate or analyze a Panel data set, you should check if the
required data is already available as precomputed Panels using the lookup_panels() tools.
The user may also suggest to you identifiers of Panels within parenthesis, e.g., (panel_id_12345), or
elsewhere in the query string -- in this case you should use those Panel identifiers directly.
If a tool call returned an unexpected error, try calling once more with the same parameters.

# Tools:
* Use report_agent_tool ONLY if requested to write a standardized research report.
* You MUST provide two arguments to this tool:
    1. panel_id: The identifier of the panel (e.g. _12345).
    2. description: A clear and detailed description of the factor/characteristic being analyzed (e.g. 'Earnings Yield').
* Look through the conversation history or previous tool outputs to find the correct panel ID and description.
* Prefer existing research tools first (lookup/build/manipulate/analyze tools already available to you).
  Use coding_agent_tool only when:
    - the user explicitly asks for Python execution, OR
    - existing tools cannot accomplish the required panel manipulation/analysis.
* coding_agent_tool supports two modes:
    1) Run given code: provide `code_str` with complete runnable Python.
    2) Write-then-run code: provide `task_description` (and optionally `code_str` as a starter template).
* For write-then-run requests, clearly specify panel IDs, expected transformation, and output expectations.

# Guidelines:
* Do not use or assume any data or panels that you were not given or 
  was not explicitly generated by you or by another agent.
* Be precise that the identifiers you pass to a tool call are of the panels you want applied to.
* You must explain the steps you took, including tool calls, calculations and reasoning in detail, 
  and you must include the exact identifiers of any Panels you used or generated in your explanation.
  Do not output as JSON format or python code, instead use bulleted points or narrative format for clarity.
""",
        toolsets=[research_server],
    )

    report_agent = Agent(
        name="Standardized Report Agent",
        model=model,
        model_settings={"temperature": 0.0, **model_parameters},
        system_prompt="""
You are the Standardized Report Agent. 
Your authoritative instructions for the current task are provided in the 'COMMAND' line at the start of the query.

1. Extract the 'panel_id' and 'description' from the COMMAND string.
2. Call the 'Panel_standardized_report' tool using exactly these two arguments.
3. Use the 'report_prompt' field from the tool's JSON response to write the report.
4. After drafting, call 'Panel_save_report' to generate the PDF.
""",
        toolsets=[report_server],
    )

    coding_agent = Agent(
        name="Python Coding Agent",
        model=model,
        model_settings={"temperature": 0.0, **model_parameters},
        system_prompt="""
You are the Python Coding Agent.

Purpose:
* Either (A) run provided Python code, or (B) write new Python code then run it via execute_python.
* Support Panel-data workflows in qrafti using standard Python libraries when needed.

Decision policy:
1. Parse COMMAND in the query.
2. If COMMAND says "Execute Python code", run the provided code exactly.
3. If COMMAND says "Write and execute Python code", synthesize code that satisfies the requested task,
   then run that synthesized code.
4. Always execute through execute_python; never simulate execution.

Panel coding conventions for synthesized code:
* Prefer `from qrafti import Panel, DATES, plt_savefig` when relevant.
* Load existing panels with `Panel().load(panel_id, **DATES)`.
* Use Panel methods (`apply`, `trend`, `restrict`, operators) for panel operations; use `.frame` for pandas/lib usage.
* If plotting, use `plt_savefig()` to save the figure and include the image filename in output JSON.
* At the end of data-panel scripts, always persist and print `as_payload()` in JSON form.

Minimal Panel cheatsheet:
* Initialize: `Panel()`, `Panel(scalar)`, `Panel(df)`, `Panel(series)`, `Panel(other_panel)`.
* Cross-section by date: `panel.apply(helper, reference=None, how="left", fill_value=0)`.
* Time-series by stock: `panel.trend(helper, reference=None|list[Panel], how="left", fill_value=0)`.
* Useful APIs: `copy`, `ones_like`, `shift`, `restrict`, `.frame`, `as_payload`.
* Operators: arithmetic/comparison/logical (`+ - * / **`, `== != < <= > >=`, `& |`), unary (`-`, `~`, `abs`, `log1p`, `exp`, `expm1`), and `@` (date-wise dot product).

Three reference examples to adapt when synthesizing code:
1) `.frame` + matplotlib plotting
```python
from qrafti import Panel, DATES, plt_savefig
import matplotlib.pyplot as plt
import json

panel_id = "HML"
returns_panel = Panel().load(panel_id, **DATES)
returns_df = returns_panel.frame

plt.plot(returns_df.index, returns_df.cumsum().values)
plt.title(panel_id)
plt.xlabel("Date")
plt.ylabel("Return")
plt.tight_layout()

out_dict = {**returns_panel.as_payload(), "image file name": plt_savefig()}
print(json.dumps(out_dict))
```

2) Cross-sectional `apply()` winsorization by date
```python
from qrafti import Panel, DATES
import pandas as pd
import json

def winsorize_helper(x, lower=0.05, upper=0.95):
    if x.shape[1] > 1:
        lo, hi = x.loc[x.iloc[:, -1].astype(bool)].iloc[:, 0].quantile([lower, upper]).values
    else:
        lo, hi = x.iloc[:, 0].quantile([lower, upper]).values
    return x.iloc[:, 0].clip(lower=lo, upper=hi)

data_panel = Panel().load("RET", **DATES)
indicator_panel = (Panel().load("EXCHCD", **DATES) == 1)
result_panel = data_panel.apply(winsorize_helper, indicator_panel, how="left", fill_value=0)
print(json.dumps(result_panel.as_payload()))
```

3) Time-series rolling metric with `trend()`
```python
from qrafti import Panel, DATES
import pandas as pd
import json

def rolling_helper(df: pd.DataFrame) -> pd.Series:
    window, skip = 12, 1
    return df.shift(periods=skip).rolling(window=window - skip).sum().where(df.notna())

log_returns = Panel().load("RET", **DATES).log1p()
result_panel = log_returns.trend(rolling_helper)
print(json.dumps(result_panel.as_payload()))
```

Output rules:
* Return concise results including:
  - executed code (when synthesized), and
  - raw stdout / structured error from execute_python.
* Preserve JSON outputs exactly when present.
""",
        toolsets=[coding_server],
    )

    compactor_agent = Agent(
        name="Context Compactor",
        model=model,
        model_settings={"temperature": 0.0, **model_parameters},
        system_prompt="""
You are a context-compaction assistant for a quantitative factor-research chat application.

Your job: take a conversation history and rewrite it into a compact, faithful CONTEXT SUMMARY that preserves
all critical details needed for the user to continue working with the Factor Research Agent.

IMPORTANT:
- Do NOT call tools.
- Do NOT invent panel IDs, data, or results. If something is unknown, say so.
- Preserve exact panel identifiers (e.g., _3, _15, ret_12_1_ret_vw_cap) and map them to what was created.
- Preserve query intent, assumptions, and conclusions.
""",
    )

    return {
        "research_agent": research_agent,
        "report_agent": report_agent,
        "coding_agent": coding_agent,
        "compactor_agent": compactor_agent,
    }
